<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AxisJogTestSuite" Id="{d58fdfa9-a16a-4795-9564-e1d5a0ea8323}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AxisJogTestSuite EXTENDS TestSuite<TestSuiteParameter.MaxTestCount>
VAR
	StubAxis : AXIS_REF;
	iStubTask : I_Task;
	TestAxisJog : JogBehaviour(stubaxis);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>