<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="AxisVelocityTestSuite" Id="{6f423009-7ac9-4bbc-9784-ede5e34ea635}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AxisVelocityTestSuite EXTENDS TestSuite<TestSuiteParameter.MaxTestCount>
VAR
	StubAxis : AXIS_REF;
	iStubTask : I_Task;
	TestAxisHalt : VelocityBehaviour(StubAxis);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>