<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{0e9c9627-95a3-4f44-9640-070a0428525d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Power_TestSuite : AxisPowerTestSuite;
	Reset_TestSuite : AxisResetTestSuite;
	Halt_TestSuite : AxisHaltTestSuite;
	Axis_TestSuite : AxisTestSuite;
	AxisJog_TestSuite : AxisJogTestSuite;
	AxisVelo_TestSuite : AxisVelocityTestSuite;
	AxisAbs_TestSuite : AxisAbsTestSuite;
	AxisMod_TestSuite : AxisModTestSuite;
	AxisRel_TestSuite : AxisRelTestSuite;
	GearOperation_TestSuite : GearOperationTestSuite;
	SoEReset_TestSuite : SoEResetTestSuite;
	ReRun: BOOL;
	i : INT;
	Integration_TestSuite : IntegrationTestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Power_TestSuite();
Reset_TestSuite();
Halt_TestSuite();
Axis_TestSuite();
AxisJog_TestSuite();
AxisVelo_TestSuite();
AxisAbs_TestSuite();
AxisMod_TestSuite();
AxisRel_TestSuite();
GearOperation_TestSuite();
SoEReset_TestSuite();

Integration_TestSuite();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>