<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="StubTask" Id="{c4b913a6-ffc3-4925-be97-7fe940dfab3e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK StubTask IMPLEMENTS I_Task
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Abort" Id="{43d6722c-87e6-488f-a2d8-23a304e3ae10}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Abort : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Busy" Id="{148822db-b76d-49e4-ac90-653df4a62c57}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{9c35da09-c523-4220-b08b-ab59892c326e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Done" Id="{6d0d6f9b-aebb-4d0d-8062-3bba4dc48f43}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{e33161b1-7930-4523-a05a-40c9b3664392}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Error" Id="{ddc0f6db-994c-4c20-ad8c-1e1474a670ba}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{88c2e8ee-f421-41cf-b239-0c98fea27289}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>